FROM node:12-alpine as build

WORKDIR "/usr/src/vocca-server"

COPY package.json .
COPY yarn.lock .
RUN yarn install

COPY . .
RUN npx tsc

FROM node:12-alpine

ARG WORKDIR=/usr/src/vocca-server
WORKDIR ${WORKDIR}

COPY --from=build ${WORKDIR}/dist ./dist
COPY ./package.json ${WORKDIR}
COPY ./yarn.lock ${WORKDIR}
RUN yarn install --production

EXPOSE 4000

CMD node ./dist/index.js